// Generated by gencpp from file hello_publisher/hello.msg
// DO NOT EDIT!


#ifndef HELLO_PUBLISHER_MESSAGE_HELLO_H
#define HELLO_PUBLISHER_MESSAGE_HELLO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_publisher
{
template <class ContainerAllocator>
struct hello_
{
  typedef hello_<ContainerAllocator> Type;

  hello_()
    : greeting()  {
    }
  hello_(const ContainerAllocator& _alloc)
    : greeting(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _greeting_type;
  _greeting_type greeting;





  typedef boost::shared_ptr< ::hello_publisher::hello_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_publisher::hello_<ContainerAllocator> const> ConstPtr;

}; // struct hello_

typedef ::hello_publisher::hello_<std::allocator<void> > hello;

typedef boost::shared_ptr< ::hello_publisher::hello > helloPtr;
typedef boost::shared_ptr< ::hello_publisher::hello const> helloConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_publisher::hello_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_publisher::hello_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hello_publisher::hello_<ContainerAllocator1> & lhs, const ::hello_publisher::hello_<ContainerAllocator2> & rhs)
{
  return lhs.greeting == rhs.greeting;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hello_publisher::hello_<ContainerAllocator1> & lhs, const ::hello_publisher::hello_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hello_publisher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hello_publisher::hello_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_publisher::hello_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_publisher::hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_publisher::hello_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_publisher::hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_publisher::hello_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_publisher::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af3498ba158bcdd555fe81847eb6e16d";
  }

  static const char* value(const ::hello_publisher::hello_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf3498ba158bcdd5ULL;
  static const uint64_t static_value2 = 0x55fe81847eb6e16dULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_publisher::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_publisher/hello";
  }

  static const char* value(const ::hello_publisher::hello_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_publisher::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string greeting\n"
;
  }

  static const char* value(const ::hello_publisher::hello_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_publisher::hello_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.greeting);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hello_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_publisher::hello_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_publisher::hello_<ContainerAllocator>& v)
  {
    s << indent << "greeting: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.greeting);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_PUBLISHER_MESSAGE_HELLO_H
